### PR TITLE
d3.time.format update

### PR DESCRIPTION
**Pull request by andrewheekin**
d3 graphs will break with trying to fit "year-month-day hour:min:sec" datetime data into the "%Y-%m-%d" format. 

d3.time.format("%Y-%m-%d %H:%M:%S") must be added.

### CODE REVIEW

**Comment by ibrahimokdadov** [comment]
Your change saved me alot of debugging. thumbs up.

**Comment by an00bhav** [comment]
I actually opened a new PR with this exact change. Didn't saw this. Closing my PR now.

**Comment by robertdavidwest** [comment]
I just did the exact same thing. No chance this PR could be merged?

**Comment by andrewheekin** [comment]
closed due to maintainer inactivity

**Comment by an00bhav** [comment]
@andrewheekin How about forking this repo and developing it ahead? If the maintainer is active again we can integrate the fork back upstream!

**Pull request closed without merging**
